### PR TITLE
Fix back button navigation with model grouping

### LINKED ISSUE #330: Handle browser history
When on the models listing the jump through the grouping then use the back button in the broswer and the UI should change to reflect the URL:

You can use the popstate method to detect those URL changes and make UI changes as needed.

```js
window.addEventListener('popstate', function (event) {
	// The URL changed...
});
```
You can access that property on the event object.

```js
window.addEventListener('popstate', function (event) {
	// Log the state data to the console
	console.log(event.state);
});
```

### PR DESCRIPTION
**Pull request by hatched**
## Done

When using the back button after toggling the model grouping it now correctly updates the UI.

## QA

- Pull code
- Run `./run clean && ./run serve`
- Open http://0.0.0.0:8036/
- Play with the model grouping buttons, they should update the UI as expected
- Hit the back button, it should navigate back through the groupings.
- Refresh with a grouping query string in the URL, it should render that grouping.

## Details

Fixes #330

### CODE REVIEW

File: src/pages/Models/Models.js [hunk 1]
```diff
@@ -22,19 +22,21 @@ export default function Models() {
...
-  // Set initial state using filter from URL
-  const [groupedBy, setGroupedBy] = useState(groupedByFilter);
-  // Assign updated filter back to queryStrings obj
-  queryStrings.groupedby = groupedBy;
-  // Stringify the obj again to push back to URL
-  const updatedQs = queryString.stringify(queryStrings);
-  // Add as an effect so UI is updated on each component render (e.g. Back button)
-  useEffect(() => {
+
+  const [groupModelsBy, setGroupModelsBy] = useState(groupedByFilter);
```
Comment (hatched) [inline src/pages/Models/Models.js]: @barrymcgee FYI Even though `groupedByFilter` was changing with the back button interactions, because the initial state of the state was already set it didn't update the `groupModelsBy` state. So the following 3 lines are used to do just that.
