### PR TITLE
fix(model details): correctly display the modelName in the expanded model topology view

### LINKED ISSUE #500: Topology can erroneously report model not loaded

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

(fix) Fall back to modelName if cannot split on slash -this prevents an erroneous "Model not loaded" message from appearing

## QA

- Pull code
- Run `./run clean && ./run serve`
- Open http://0.0.0.0:8036/
- Go to model details pages, expand topologies and verify the title of the model appears correctly

## Details

Fixes #500

### CODE REVIEW

File: src/components/InfoPanel/InfoPanel.js [hunk 1]
```diff
@@ -66,7 +66,7 @@ const InfoPanel = () => {
       {showExpandedTopology ? (
         <Modal
           close={() => setShowExpandedTopology(false)}
-          title={modelName.split("/")[1] || "Error: model not loaded..."}
+          title={modelName.split("/")[1] || modelName}
```
Comment (hatched) [inline src/components/InfoPanel/InfoPanel.js:69]: You'll still want to keep the old fallback as a third option as that was added to resolve another issue.

Comment (barrymcgee) [reply src/components/InfoPanel/InfoPanel.js:69]: The original issue was preventing a blank value if the model name could not be split on slash... this change addresses that already.
