### PR TITLE
Controller connection reliability improvements

### LINKED ISSUE #105: Controller connection disconnects before subsequent modelInfo calls can be made
**Describe the bug**
The controller connection appears to disconnect after a short period of time. If you leave the application running you'll eventually see it time out. It's possible we have to enable the pinger to keep the connection alive. With a sufficiently large list of models the model status requests take too long and the next controller request falls outside the 'keep alive' time limit.

**To Reproduce**
1. Open application and have it list the models
2. Open the devtools and wait
3. The controller connection will time out.

**Screenshots**
Screen Shot 2019-10-23 at 12 22 37 PM

### PR DESCRIPTION
**Pull request by hatched**
## Done

- When connecting to a controller, start the pinger on 20s increments to keep the controller connection alive. This is required because the controller interactions can be spaced out longer than the 1m timeout in the event the user has a large number of models we're polling against.
- If a model connection takes longer than 5s then abandon the connection. This was necessary because sometimes model connections hang, which prevents the poller from starting over again as something is always stuck in the queue.

## QA

- Pull code
- Run `./run clean && ./run serve`
- Open http://0.0.0.0:8036/
- The model list should work as expected
- To test the failure case, change the timeout to 50ms from 5000ms and reload. The console should have a number of console errors that an item has timed out.

## Details

Fixes #105

### CODE REVIEW

File: src/juju/index.js [hunk 1]
```diff
@@ -80,12 +87,42 @@ async function loginWithBakery(visitPage, macaroonStore) {
   }
   const juju = await jujulib.connect(
     controllerURL,
-    generateConnectionOptions()
+    generateConnectionOptions(true)
   );
   const conn = await juju.login({});
+  // Ping to keep the connection alive.
+  conn.facades.pinger.pingForever(20000, err => {
```
Comment (anthonydillon) [inline src/juju/index.js]: Is it worth checking if pinger is a member of facades here for cases when usePinger is false?

File: src/juju/index.js [hunk 2]
```diff
@@ -80,12 +87,42 @@ async function loginWithBakery(visitPage, macaroonStore) {
...
+    if (err) {
+      console.log("unable to ping:", err);
```
Comment (anthonydillon) [inline src/juju/index.js]: Should this be a console.error so we get reports from sentry?

File: src/juju/index.js [hunk 3]
```diff
@@ -80,12 +87,42 @@ async function loginWithBakery(visitPage, macaroonStore) {
...
+    }
+  });
   return { bakery, conn };
 }
 
+/**
+  Commects and logs in to the supplied modelURL. If the connection takes longer
```
Comment (anthonydillon) [inline src/juju/index.js]: Typo: Connects

File: src/juju/reducers.js [hunk 4]
```diff
@@ -53,7 +53,13 @@ export default produce(
         // There don't appear to be any irrelevent data in the modelInfo so
         // we overwrite the whole object every time it changes even though
         // mostly that'll just be status timestamps.
-        draftState.modelData[modelInfo.uuid].info = modelInfo;
+        const modelData = draftState.modelData[modelInfo.uuid];
+        // If any of the status requests timeout then it's possible the data
+        // won't be available. Just abandon saving any data in that case.
+        // This will go away with the new API.
+        if (modelData) {
+          draftState.modelData[modelInfo.uuid].info = modelInfo;
```
Comment (anthonydillon) [inline src/juju/reducers.js]: Why not use `modelData.infro = modelInfo;` instead of accessing the full object again? It made me reread this conditional to make sense of it.

File: src/juju/index.js (hunk 1 above)
Comment (hatched) [reply src/juju/index.js]: For this connection `pinger` should never be undefined as it's included in the generated options above. 

I think I'd prefer it to fail dramatically then silently fail when the pinger doesn't keep the connection alive.

File: src/juju/index.js (hunk 2 above)
Comment (hatched) [reply src/juju/index.js]: We don't have sentry yet but yep I can change that.

```suggestion
      console.error("unable to ping:", err);
```

File: src/juju/index.js (hunk 3 above)
Comment (hatched) [reply src/juju/index.js]: Thanks!
```suggestion
  Connects and logs in to the supplied modelURL. If the connection takes longer
```

File: src/juju/reducers.js (hunk 4 above)
Comment (hatched) [reply src/juju/reducers.js]: I was being explicit because `draftState` is a proxy supplied by the library `immer` that we use for immutable state.
