### PR TITLE
Fix icon colors in sidebar

### LINKED ISSUE #307: Icons in the left nav are the wrong colour
The icons in the left navigation should be #CDCDCD (`color-mid-light`), and then #FFFFFF (`color-x-light`) when selected.

[Design on Zeplin](https://zpl.io/a3dqpAy).

Thanks.

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

Fix icon colors in sidebar and provide alternatives for selected states.

## QA

- Pull code
- Run `./run clean && ./run serve`
- Open http://0.0.0.0:8036/

Fixes #307

### CODE REVIEW

File: src/components/PrimaryNav/PrimaryNav.js [hunk 1]
```diff
@@ -119,6 +131,8 @@ const PrimaryNav = () => {
               className="p-list__link"
               isActive={match => {
                 if (match && match.url.includes(navItem.path)) {
+                  console.log(navItem.path);
```
Comment (hatched) [inline src/components/PrimaryNav/PrimaryNav.js]: left over log
